spring:
  application:
    name: gemini
  datasource:
    #url: jdbc:mysql://localhost:3306/app?autoReconnect=true&useSSL=false
    url: jdbc:log4jdbc:mysql://localhost:3306/app?autoReconnect=true&useSSL=false
    username: root
    #password: app
    #driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
