spring:
  application:
    name: gemini
  datasource:
    url: jdbc:mysql://localhost:23306/gemini?allowPublicKeyRetrieval=true&useSSL=false
    username: gemini
    password: gemini
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:23306/gemini?allowPublicKeyRetrieval=true&useSSL=false
    user: gemini
    password: gemini

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE